#   === Client DB - SQL =====

spring.datasource.client.jdbc-url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.client.username=shanthi
spring.datasource.client.password=admin
spring.datasource.client.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
